---
go: 
  version: 1.14
verbose: true
repository:
  path: github.com/leominov/network-access-exporter
build:
  flags: -a -tags netgo
  ldflags: |
    -s
    -X github.com/prometheus/common/version.Version={{.Version}}
    -X github.com/prometheus/common/version.Revision={{.Revision}}
    -X github.com/prometheus/common/version.Branch={{.Branch}}
    -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
    -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
  files:
    - LICENSE
    - README.md
    - config.example.yaml
crossbuild:
  platforms:
    - linux/amd64
    - linux/386
    - darwin/amd64
    - darwin/386
    - windows/amd64
    - windows/386
